WIDTH = 800
HEIGHT = 800
NUM_NODES = 300
CLICK_RADIUS = 50
LIVE = True
CSV_FILE = "simulation.csv"

REPULSION_STRENGTH = 10
PULL_TO_CENTER_STRENGTH = 0

AGGREGATION_MIDPOINT = 200   
AGGREGATION_STEEPNESS = 1

FRICTION_STRENGTH = 10

SHOW_VORONOI_BOUNDARIES = False
SHOW_VORONOI_BEZIERS = True
VORONOI_BEZIER_INSET = 30
